### ISSUE TITLE
bs-next fails when included with latest bs-platform

### ISSUE THREAD

**Issue by Enalmada** [ulrikstrid/bs-next#10]
Thank you for contributing this binding to the community.  Without it, I would not have been able to play around with next.js and reason-react.   Older versions of bs-platform have issues on windows so I have had to update it in my next.js project to get examples/with-reasonml working...but the latest version of bs-platform causes bs-next to throw a runtime error.  If I include Next.rc directly into my project it works fine so it must be a compile version incompatibility.  At your convenience, could you update the dependencies and do a release?

**Comment by ulrikstrid** [comment]
I would love a PR!

If you don't have time I'll try to get to it as soon as possible, I'm not really using next at the moment so it's hard to make time for it.

**Comment by Enalmada** [comment]
Yes, I should learn how to get something like bs-next working locally so I can test it.   Fortunately there doesn't seem to be a rush since it seems to works fine when placed directly into project and hopefully this ticket will help any new users realize that until one of us gets around to this.
